version: "3.5"

services:
  config-server:
    image: config-server
    build:
      context: ./app
      dockerfile: Dockerfile
      target: runner
    container_name: config-server.local
    hostname: config-server.local
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
    depends_on:
      - mysql
  mysql:
    image: mysql:8-oracle
    container_name: mysql.local
    hostname: mysql.local
    ports:
      - 3306:3306
    volumes:
      - ./mysql/database:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
    env_file: ./config/DEV.env
