version: "3.5"

services:
  config-server:
    image: config-server
    build:
      context: ./app
      dockerfile: Dockerfile
      target: runner
    container_name: config-server.local
    hostname: config-server.local
    ports:
      - 8010:8000
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
    depends_on:
      - mysql
  mysql:
    image: mysql:8-oracle
    container_name: mysql.local
    hostname: mysql.local
    ports:
      - 3306:3306
    volumes:
      - ./mysql/database:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    env_file: ./config/DEV.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq.local
    hostname: rabbitmq.local
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_PID_FILE=/var/lib/rabbitmq/mnesia/rabbitmq
    #command: >
    #  bash -c "/scripts/init.sh && echo 'hello'"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq # data mapping -> host: container
    #- ./rabbitmq/init.sh:/scripts/init.sh
    #- ./rabbitmq/init_check.sh:/scripts/init_check.sh
    
